name: ghci-dap
version: '0.0.13.0'
synopsis: ghci-dap is a GHCi having DAP interface.
description: Please see README.md
category: Development
author: phoityne_hs
maintainer: phoityne.hs@gmail.com
copyright: 2017-2020 phoityne_hs
license: BSD3
homepage: https://github.com/phoityne/ghci-dap
bug-reports: https://github.com/phoityne/ghci-dap/issues
extra-source-files:
- README.md
- Changelog.md
- src-c-8.4/HsVersions.h
- src-c-8.4/PosixSource.h
- src-c-8.6/PosixSource.h
- src-c-8.8/PosixSource.h

when:
- condition: impl(ghc < 8.4.0)
  dependencies: unsupported-ghc-version > 1 && < 1

dependencies:
- base >=4.7 && <5
- ghc
- ghci
- ghc-paths
- ghc-prim
- transformers
- containers
- time
- directory
- haskeline
- array
- process
- ghc-boot
- filepath
- bytestring
- deepseq
- text
- haskell-dap >= 0.0.14.0

library:
  source-dirs: src
  exposed-modules:
  - GHCi.DAP

executables:
  ghci-dap:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -fno-warn-unused-do-bind
    - -fno-warn-name-shadowing
    cc-options: -fPIC
    cpp-options: -DGHCI
    dependencies:
    - ghci-dap

    when:
    - condition: (impl(ghc >= 8.4.0)) && (impl(ghc < 8.5.0))
      source-dirs: app-ghc-8.4
      c-sources: src-c-8.4/hschooks.c
      include-dirs:
      - src-c-8.4/

    - condition: (impl(ghc >= 8.6.0)) && (impl(ghc < 8.7.0))
      source-dirs: app-ghc-8.6
      c-sources: src-c-8.6/hschooks.c
      include-dirs:
      - src-c-8.6/

    - condition: (impl(ghc >= 8.8.1)) && (impl(ghc < 8.9.0))
      source-dirs: app-ghc-8.8
      c-sources: src-c-8.8/hschooks.c
      include-dirs:
      - src-c-8.8/

    - condition: os(windows)
      then:
        dependencies:
        - Win32
      else:
        dependencies:
        - unix

